// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinemaLibrary.Infrastructure.Models
{
    public partial class Favourites
    {
        public Guid favouriteId { get; set; }
        public Guid movieId { get; set; }
    }
}