// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CinemaLibrary.Infrastructure.Models
{
    public partial class Movies
    {
        public Guid movieId { get; set; }
        public Guid categoryId { get; set; }
        public int movieLength { get; set; }
        public float movieRating { get; set; }
        public string movieName { get; set; }
    }
}